// generated by mBlock5 for mBot Ranger
// codes make you happy

#include <Arduino.h>
#include <MeAuriga.h>

MeRGBLed rgbled_0(0, 12);                     // create rgbled object 

void setup() {
  rgbled_0.setpin(44);                        // init set PIN to D44
}

void loop() {
  for (int light = 1; light < 13; light++) {
    rgbled_0.setColor(light, 255, 0, 0);      // Set light to red
    rgbled_0.show();
    delay(100);
    rgbled_0.setColor(light, 0, 0, 0);        // turn light off
    rgbled_0.show();
  }
}
