// generated by mBlock5 for mBot Ranger
// codes make you happy

#include <Arduino.h>
#include <MeAuriga.h>

MeRGBLed rgbled_0(0, 12);

void setup() {
  rgbled_0.setpin(44);
  rgbled_0.fillPixelsBak(0, 2, 1);
}

void _loop() {
  for (int count2 = 0; count2 < 12; count2++) {
    count = (count + 1);

    rgbled_0.setColor(count, 255, 0, 0);
    rgbled_0.show();
    delay(1);
    rgbled_0.setColor(count, 0, 0, 0);
    rgbled_0.show();
  }
}

