// generated by mBlock5 for mBot Ranger
// codes make you happy

#include <Arduino.h>
#include <MeAuriga.h>

MeBuzzer buzzer;                      // create buzzer object
const int delay_note = 20;            // delay before playing next note

void setup() {
  buzzer.setpin(45);                  // init buzzer on pin D45

  buzzer.tone(392, 0.15 * 1000);      // tone(freq in Hz, duration in mS)
  delay(delay_note);

  buzzer.tone(392, 0.15 * 1000);
  delay(delay_note);

  buzzer.tone(392, 0.25 * 1000);
  delay(delay_note);

  buzzer.tone(330, 0.5 * 1000);
  delay(delay_note);

  buzzer.tone(349, 0.15 * 1000);
  delay(delay_note);

  buzzer.tone(349, 0.15 * 1000);
  delay(delay_note);

  buzzer.tone(349, 0.25 * 1000);
  delay(delay_note);

  buzzer.tone(294, 0.5 * 1000);
  delay(delay_note);
}

void loop() {
}
